
server:
    port: 8080
    contextPath: /client
    ssl:
      enabled: true
      key-store: classpath:client.jks
      key-alias: client-ssl
      key-store-password: test-store-pass
      key-password: test-key-pass
      trust-store: classpath:client-trust-store.jks
      trust-store-password: test-store-pass
      
security:
    basic:
        enabled: false

config:
  oauth2:
    a-service:    
        clientID: my-client-with-registered-redirect
        clientSecret: 
        accessTokenUri: https://localhost:9090/oauth/token
        userAuthorizationUri: https://localhost:9090/oauth/authorize
        scopes: read
        resourceUri: https://localhost:9091
        redirectUri: https://localhost:8080/client/me
        logoutUri: https://localhost:9090/logout
                
logging.level.org.springframework.security.oauth2: DEBUG     